name: Build and Deploy Container to ACR + App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login to Azure with Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACR_SP_APPID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Set variables
      - name: Set variables
        id: vars
        run: |
          echo "ACR_NAME=${{ secrets.ACR_NAME }}" >> $GITHUB_ENV
          echo "AZURE_RG=${{ secrets.AZURE_RG }}" >> $GITHUB_ENV
          LOGIN_SERVER=$(az acr show --name ${{ secrets.ACR_NAME }} --query loginServer -o tsv)
          echo "LOGIN_SERVER=$LOGIN_SERVER" >> $GITHUB_ENV
          IMAGE_NAME=$LOGIN_SERVER/${{ github.repository }}:latest
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "Using image: $IMAGE_NAME"

      # 4. ACR Docker Login
      - name: ACR Docker Login
        run: |
          az acr login --name $ACR_NAME

      # 5. Build and Push Docker Image
      - name: Build and Push Image
        run: |
          docker build -t $IMAGE_NAME -f Dockerfile.backend .
          docker push $IMAGE_NAME

      # 6. Configure Web App to Use Container
      - name: Deploy to Web App
        run: |
          az webapp config container set \
            --name tchamna-rag-ai-foundations-demo \
            --resource-group $AZURE_RG \
            --docker-custom-image-name $IMAGE_NAME \
            --docker-registry-server-url https://$LOGIN_SERVER \
            --docker-registry-server-user ${{ secrets.ACR_SP_APPID }} \
            --docker-registry-server-password ${{ secrets.ACR_SP_PASSWORD }}

          az webapp config appsettings set \
            --resource-group $AZURE_RG \
            --name tchamna-rag-ai-foundations-demo \
            --settings WEBSITES_PORT=8000

      # 7. Restart Web App (so it pulls the new container)
      - name: Restart Web App
        run: |
          az webapp restart \
            --name tchamna-rag-ai-foundations-demo \
            --resource-group $AZURE_RG
