name: Build and Deploy Container to ACR + App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set variables
        run: |
          echo "ACR_NAME=ragfoundationsdemoregistry" >> $GITHUB_ENV
          echo "AZURE_RG=rag-ai-foundations-demo-rg" >> $GITHUB_ENV
          echo "APP_SERVICE_NAME=tchamna-rag-ai-foundations-demo" >> $GITHUB_ENV
          LOGIN_SERVER=$(az acr show --name ragfoundationsdemoregistry --query loginServer -o tsv)
          echo "LOGIN_SERVER=$LOGIN_SERVER" >> $GITHUB_ENV
          IMAGE_NAME=$LOGIN_SERVER/rag_ai_backend:latest
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build and Push Image
        run: |
          az acr login --name $ACR_NAME
          docker build -t $IMAGE_NAME -f Dockerfile.backend .
          docker push $IMAGE_NAME

      - name: Deploy to Web App
        run: |
          az webapp config container set \
            --name $APP_SERVICE_NAME \
            --resource-group $AZURE_RG \
            --container-image-name $IMAGE_NAME \
            --container-registry-url https://$LOGIN_SERVER

          az webapp config appsettings set \
            --resource-group $AZURE_RG \
            --name $APP_SERVICE_NAME \
            --settings WEBSITES_PORT=8000

      - name: Restart Web App
        run: |
          az webapp restart \
            --name $APP_SERVICE_NAME \
            --resource-group $AZURE_RG
