name: Build backend image and deploy to ACR + App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure (service principal)
        run: |
          az login --service-principal -u ${{ secrets.ACR_SP_APPID }} -p '${{ secrets.ACR_SP_PASSWORD }}' --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set variables
        id: vars
        run: |
          ACR_NAME=${{ secrets.ACR_NAME }}
          if [ -z "$ACR_NAME" ]; then
            echo "ACR_NAME is not set. Please add repository secret ACR_NAME with your Azure Container Registry name." >&2
            exit 1
          fi
          LOGIN_SERVER=$(az acr show --name "$ACR_NAME" --query loginServer -o tsv)
          echo "LOGIN_SERVER=$LOGIN_SERVER" >> $GITHUB_OUTPUT
          IMAGE_NAME="$LOGIN_SERVER/${{ github.repository }}:latest"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Set AZURE_RG env
        run: |
          echo "AZURE_RG=${{ secrets.AZURE_RG }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements for ACR helper
        run: |
          python -m pip install --upgrade pip

      - name: Run push_to_acr script
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          AZURE_RG: ${{ secrets.AZURE_RG }}
          ACR_SP_APPID: ${{ secrets.ACR_SP_APPID }}
          ACR_SP_PASSWORD: ${{ secrets.ACR_SP_PASSWORD }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          python scripts/push_to_acr.py --acr-name "$ACR_NAME" --repo "${{ github.repository }}" --tag latest --dockerfile Dockerfile.backend --context . --configure-webapp --app-name tchamna-rag-ai-foundations-demo --resource-group "$AZURE_RG"
