name: Build backend image and deploy to ACR + App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38DE833436A341C0A545448B11A88D9F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B88B45F0C5574C009FE3EA62FD610580 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C23CE36AE8084CF1ADB1219965C42869 }}

      - name: Set variables
        id: vars
        run: |
          ACR_NAME=${{ secrets.ACR_NAME }}
          if [ -z "$ACR_NAME" ]; then
            echo "ACR_NAME is not set. Please add repository secret ACR_NAME with your Azure Container Registry name." >&2
            exit 1
          fi
          LOGIN_SERVER=$(az acr show --name "$ACR_NAME" --query loginServer -o tsv)
          echo "LOGIN_SERVER=$LOGIN_SERVER" >> $GITHUB_OUTPUT
          IMAGE_NAME="$LOGIN_SERVER/${{ github.repository }}:latest"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Set AZURE_RG env
        run: |
          echo "AZURE_RG=${{ secrets.AZURE_RG }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements for ACR helper
        run: |
          python -m pip install --upgrade pip

      - name: Run push_to_acr script
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          AZURE_RG: ${{ secrets.AZURE_RG }}
        run: |
          python scripts/push_to_acr.py --acr-name "$ACR_NAME" --repo "${{ github.repository }}" --tag latest --dockerfile Dockerfile.backend --context . --configure-webapp --app-name tchamna-rag-ai-foundations-demo --resource-group "$AZURE_RG"
