# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - tchamna-rag-ai-foundations-demo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # 3.13 is too new, many ML libs may not support it

      # 🧹 Free space
      - name: Clean up runner
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
          sudo rm -rf /usr/local/share/dotnet || true
          df -h

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create venv & Install base requirements
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements-base.txt

      - name: Install ML requirements separately
        run: |
          source antenv/bin/activate
          pip install -r requirements-ml.txt || echo "ML deps installed with warnings"
                
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38DE833436A341C0A545448B11A88D9F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B88B45F0C5574C009FE3EA62FD610580 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C23CE36AE8084CF1ADB1219965C42869 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tchamna-rag-ai-foundations-demo'
          slot-name: 'Production'
