name: Build and deploy Python app to Azure Web App - tchamna-rag-ai-foundations-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment, install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/
            !.git/
            !.github/
            !__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F5CDC0F80638430D8766CA02F8B5AC26 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8C6CEF7FC8E740869F9990AB93966567 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9D8C22EDA8A44F3DB8253C2A2661E4B9 }}

      # 🧹 NEW: Clean wwwroot before deploying (no resource group reference)
      - name: Clean existing files in Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            echo "Cleaning /home/site/wwwroot on Azure App Service..."
            az webapp ssh \
              --name tchamna-rag-ai-foundations-demo \
              --command "rm -rf /home/site/wwwroot/* || true"
            echo "Clean complete."

      # 🚀 Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'tchamna-rag-ai-foundations-demo'
          slot-name: 'Production'
