name: Build and Deploy Python app to Azure Web App - tchamna-rag-ai-foundations-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # App Service supports 3.10

      - name: Install dependencies (validate build)
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            . 
            !antenv/
            !.git/
            !__pycache__/
            !*.pyc
            !.venv/
            !env/
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write    # needed for OIDC
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tchamna-rag-ai-foundations-demo'
          slot-name: 'Production'

      - name: Set startup command for Streamlit
        run: |
          az webapp config set \
            --resource-group rag-ai-foundations-demo-rg \
            --name tchamna-rag-ai-foundations-demo \
            --startup-file "streamlit run app.py --server.port=8000 --server.address=0.0.0.0"
