name: Precompute embeddings

on:
  workflow_dispatch:
  # push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run precompute
        run: |
          python src/precompute_embeddings.py
      - name: Upload vectorstore
        uses: actions/upload-artifact@v4
        with:
          name: vectorstore
          path: vectorstore
